# Resynthesize Janszen Legacy Project data 
# Based on iNat taxon correspondences generated by Antranig Basman (Dec 2022)
# 2022-12-10
# Andrew Simon

# Set relative paths (https://stackoverflow.com/questions/13672720/r-command-for-setting-working-directory-to-source-file-location-in-rstudio)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 

# Load packages

library(dplyr)
library(stringr)
library(tidyr)

# Read original comprehensive plant lists for Saanich Peninsula, Southern Gulf Islands, San Juans
# Based on records compiled by Harvey Janszen and by Peter Dunwiddie and Adam Martin

Janszen.OGIs <- read.csv("Janszen_Comprehensive_Summaries_2022/Outer_Gulf_Island_Plant_List_2021-12-13.csv")
Janszen.SSI <- read.csv("Janszen_Comprehensive_Summaries_2022/Salt_Spring_Island_Plant_List_2021-12-13.csv")
Janszen.Saanich <- read.csv("Janszen_Comprehensive_Summaries_2022/Saanich_Peninsula_Plant_List_2021-12-13.csv")
Janszen.San.Juans <- read.csv("Janszen_Comprehensive_Summaries_2022/San_Juan_Islands_Plant_List_2021-12-13.csv")
Dunwiddie.Martin.San.Juans <- read.csv("Dunwiddie_and_Martin_2022/sji_master_flora.csv")
Dunwiddie.Martin.San.Juans.AS <- read.csv("Dunwiddie_and_Martin_2022/sji_master_flora_iNat_names_&_families.csv")

# Read reintegrated lists matching records with taxa on iNaturalist

Janszen.reintegrated <- read.csv("Janszen_Comprehensive_Summaries_2022/reintegrated.csv")
Dunwiddie.reintegrated <- read.csv("Dunwiddie_and_Martin_2022/assigned-Dunwiddie.csv")

# Merge records to assign corresponding iNaturalist names and determine mismatches
# Janszen records

Janszen.OGIs$iNat_taxon <- Janszen.reintegrated$iNaturalist.taxon.name[match(unlist(Janszen.OGIs$TaxonName), Janszen.reintegrated$Taxon.name)]
Janszen.OGIs$Family <- Janszen.reintegrated$Family[match(unlist(Janszen.OGIs$iNat_taxon), Janszen.reintegrated$iNaturalist.taxon.name)]

Janszen.SSI$iNat_taxon <- Janszen.reintegrated$iNaturalist.taxon.name[match(unlist(Janszen.SSI$TaxonName), Janszen.reintegrated$Taxon.name)]
Janszen.SSI$Family <- Janszen.reintegrated$Family[match(unlist(Janszen.SSI$iNat_taxon), Janszen.reintegrated$iNaturalist.taxon.name)]

Janszen.Saanich$iNat_taxon <- Janszen.reintegrated$iNaturalist.taxon.name[match(unlist(Janszen.Saanich$TaxonName), Janszen.reintegrated$Taxon.name)]
Janszen.Saanich$Family <- Janszen.reintegrated$Family[match(unlist(Janszen.Saanich$iNat_taxon), Janszen.reintegrated$iNaturalist.taxon.name)]

Janszen.San.Juans$iNat_taxon <- Janszen.reintegrated$iNaturalist.taxon.name[match(unlist(Janszen.San.Juans$TaxonName), Janszen.reintegrated$Taxon.name)]
Janszen.San.Juans$Family <- Janszen.reintegrated$Family[match(unlist(Janszen.San.Juans$iNat_taxon), Janszen.reintegrated$iNaturalist.taxon.name)]

# Merge records to assign corresponding iNaturalist names and determine mismatches
# Dunwiddie & Martin recods

Dunwiddie.Martin.San.Juans$iNat_taxon <- Dunwiddie.reintegrated$Referred.iNaturalist.Name[match(unlist(Dunwiddie.Martin.San.Juans$Full.Species), Dunwiddie.reintegrated$Full.Species)]
Dunwiddie.Martin.San.Juans$iNat_Family <- Dunwiddie.reintegrated$family[match(unlist(Dunwiddie.Martin.San.Juans$iNat_taxon), Dunwiddie.reintegrated$Referred.iNaturalist.Name)]

# Assess mismatches in family names (iNat vs Dunwiddie)

Dunwiddie.taxon <- Dunwiddie.Martin.San.Juans$Full.Species
Dunwiddie.family <- Dunwiddie.Martin.San.Juans$Family
Dunwiddie.iNat.family <- Dunwiddie.Martin.San.Juans$iNat_Family

Dunwiddie.family.names <- data.frame(Dunwiddie.taxon,Dunwiddie.family)
colnames(Dunwiddie.family.names) <- c('Taxon','Family')
Dunwiddie.iNat.family.names <- data.frame(Dunwiddie.taxon,Dunwiddie.iNat.family)
colnames(Dunwiddie.iNat.family.names) <- c('Taxon','Family')

Dunwiddie.mismatched.family.names <- anti_join(Dunwiddie.family.names,Dunwiddie.iNat.family.names)

Dunwiddie.mismatched.family.names$iNat_Family <- Dunwiddie.reintegrated$family[match(unlist(Dunwiddie.mismatched.family.names$Taxon), Dunwiddie.reintegrated$Full.Species)]

# Assess mismatches between Dunwiddie and Martin's San Juan flora vs Janszen's San Juan flora

Dunwiddie.SJI.family <- Dunwiddie.Martin.San.Juans.AS$Family
Dunwiddie.SJI.taxon <- Dunwiddie.Martin.San.Juans.AS$iNat.Taxon

Janszen.SJI.family <- Janszen.San.Juans$Family
Janszen.SJI.taxon <- Janszen.San.Juans$iNat_taxon

Dunwiddie.SJI <- data.frame(Dunwiddie.SJI.family,Dunwiddie.SJI.taxon)
colnames(Dunwiddie.SJI) <- c('Family','Taxon')

Janszen.SJI <- data.frame(Janszen.SJI.family,Janszen.SJI.taxon)
colnames(Janszen.SJI) <- c('Family','Taxon')

Janszen.diff.Dunwiddie.SJI <- anti_join(Janszen.SJI,Dunwiddie.SJI)
Janszen.diff.Dunwiddie.SJI$HJ_comment <- Janszen.San.Juans$HJ_comment[match(unlist(Janszen.diff.Dunwiddie.SJI$Taxon), Janszen.San.Juans$iNatTaxon)]
Janszen.diff.Dunwiddie.SJI$Taxon <- Janszen.San.Juans$TaxonName[match(unlist(Janszen.diff.Dunwiddie.SJI$Taxon), Janszen.San.Juans$iNatTaxon)]

# Write CSVs

write.csv(Janszen.OGIs, "Outputs/Janszen_OGIs_iNat_names.csv")
write.csv(Janszen.SSI, "Outputs/Janszen_SSI_iNat_names.csv")
write.csv(Janszen.Saanich, "Outputs/Janszen.Saanich_iNat_names.csv")
write.csv(Janszen.San.Juans, "Outputs/Janszen.San.Juans_iNat_names.csv")
write.csv(Dunwiddie.Martin.San.Juans, "Outputs/Dunwiddie_Martin_San_Juans_iNat_names.csv")
write.csv(Dunwiddie.mismatched.family.names, "Outputs/Dunwiddie_mismatched_family_names.csv")
write.csv(Janszen.diff.Dunwiddie.SJI, "Outputs/Dunwiddie_&_Martin_vs_Janszen_mismatched_taxa")
